/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * QmlTS Engine instance.
 *
 * This class wraps Qt's QGuiApplication and QQmlEngine.
 * It is created via `createEngine()` and automatically cleaned up
 * when garbage collected, or can be explicitly destroyed via `destroyEngine()`.
 *
 * @example
 * ```typescript
 * const engine = createEngine();
 * loadString(engine, 'import QtQuick; Item { }');
 * processEvents(engine);
 * destroyEngine(engine);
 * ```
 */
export declare class QmltsEngine {

}

/**
 * Read an integer property from the active runtime QObject.
 *
 * Returns the property value if a bridge is registered and the property
 * exists on the runtime object. Returns `null` if no bridge is active
 * or the property is not found.
 *
 * @param engine - The engine instance.
 * @param name - The property name (e.g., "invokeCount", "mountedCount").
 * @returns The integer property value, or `null`.
 *
 * @example
 * ```typescript
 * registerViewModel(engine, 'LoginViewModel');
 * loadString(engine, qml);
 * processEvents(engine);
 * const count = activeRuntimeI32Property(engine, 'invokeCount');
 * ```
 */
export declare export declare function activeRuntimeI32Property(engine: QmltsEngine, name: string): number | null

/**
 * Add a QML import search path.
 *
 * @param engine - The engine instance.
 * @param path - Directory path to add to import search paths.
 *
 * @example
 * ```typescript
 * addImportPath(engine, './qml/imports');
 * ```
 */
export declare export declare function addImportPath(engine: QmltsEngine, path: string): void

/**
 * Add a Qt plugin search path.
 *
 * @param engine - The engine instance.
 * @param path - Directory path to add to plugin search paths.
 *
 * @example
 * ```typescript
 * addPluginPath(engine, '/opt/qt/plugins');
 * ```
 */
export declare export declare function addPluginPath(engine: QmltsEngine, path: string): void

/**
 * Create a new QmlTS engine instance.
 *
 * Initializes Qt's QGuiApplication (if not already initialized) and
 * creates a new QQmlEngine for loading and running QML documents.
 *
 * @param config - Optional engine configuration.
 * @returns A new QmltsEngine instance.
 * @throws Error if Qt initialization fails.
 *
 * @example
 * ```typescript
 * // Create with defaults
 * const engine = createEngine();
 *
 * // Create with custom paths
 * const engine = createEngine({
 *   importPaths: ['./qml'],
 *   enableLogging: true
 * });
 * ```
 */
export declare export declare function createEngine(config?: EngineConfig | undefined | null): QmltsEngine

/**
 * Destroy an engine instance.
 *
 * Explicitly releases engine resources. This is optional since the engine
 * will be automatically cleaned up when garbage collected.
 *
 * @param engine - The engine instance to destroy.
 *
 * @example
 * ```typescript
 * const engine = createEngine();
 * // ... use engine ...
 * destroyEngine(engine);
 * ```
 */
export declare export declare function destroyEngine(engine: QmltsEngine): void

/**
 * Engine configuration options.
 *
 * These options control Qt plugin/import paths and logging behavior.
 */
export interface EngineConfig {
  /** Qt plugin search paths. */
  pluginPaths?: string[] | undefined
  /** QML import search paths. */
  importPaths?: string[] | undefined
  /** Enable Qt logging forwarding. */
  enableLogging?: boolean | undefined
}

/**
 * Start the Qt event loop (blocking).
 *
 * This starts the Qt event loop and blocks until `quit()` is called.
 * Use `processEvents()` for non-blocking event processing.
 *
 * @param engine - The engine instance.
 * @returns Exit code from the event loop.
 *
 * @example
 * ```typescript
 * const exitCode = exec(engine);
 * console.log(`Exited with code ${exitCode}`);
 * ```
 */
export declare export declare function exec(engine: QmltsEngine): number

/**
 * Read a property value from the active ViewModel as a JSON string.
 *
 * @param engine - The engine instance.
 * @param class_name - ViewModel class name (must match the active bridge).
 * @param property_name - Property name to read.
 * @returns JSON-encoded property value.
 * @throws Error if the class name doesn't match or property not found.
 *
 * @example
 * ```typescript
 * const value = getProperty(engine, 'LoginViewModel', 'username');
 * // '"alice"'
 * ```
 */
export declare export declare function getProperty(engine: QmltsEngine, className: string, propertyName: string): string

/**
 * Get all registered bridge type names.
 *
 * @param engine - The engine instance.
 * @returns Sorted array of ViewModel class names.
 *
 * @example
 * ```typescript
 * const types = getRegisteredTypes(engine);
 * // ['CounterViewModel', 'LoginViewModel']
 * ```
 */
export declare export declare function getRegisteredTypes(engine: QmltsEngine): Array<string>

/**
 * Check whether a bridge type is available.
 *
 * @param engine - The engine instance.
 * @param class_name - ViewModel class name to check.
 * @returns `true` if the bridge type exists in the registry.
 *
 * @example
 * ```typescript
 * if (hasBridgeType(engine, 'LoginViewModel')) {
 *   registerViewModel(engine, 'LoginViewModel');
 * }
 * ```
 */
export declare export declare function hasBridgeType(engine: QmltsEngine, className: string): boolean

/**
 * Load a QML document from a file.
 *
 * @param engine - The engine instance.
 * @param path - Path to the QML file.
 * @throws Error if the file is not found or contains QML errors.
 *
 * @example
 * ```typescript
 * loadFile(engine, './app/Main.qml');
 * ```
 */
export declare export declare function loadFile(engine: QmltsEngine, path: string): void

/**
 * Load a QML document from a string.
 *
 * @param engine - The engine instance.
 * @param qml_source - QML source code.
 * @param base_url - Optional base URL for resolving relative imports.
 * @throws Error if the QML contains syntax errors.
 *
 * @example
 * ```typescript
 * loadString(engine, `
 *   import QtQuick
 *   Item {
 *     width: 400
 *     height: 300
 *   }
 * `);
 * ```
 */
export declare export declare function loadString(engine: QmltsEngine, qmlSource: string, baseUrl?: string | undefined | null): void

/**
 * Process all pending Qt events.
 *
 * This processes the Qt event queue and returns immediately.
 * Call this in a loop or timer for non-blocking event processing.
 *
 * @param engine - The engine instance.
 *
 * @example
 * ```typescript
 * // Non-blocking event processing
 * setInterval(() => processEvents(engine), 16); // ~60fps
 * ```
 */
export declare export declare function processEvents(engine: QmltsEngine): void

/**
 * Process Qt events for up to the specified duration.
 *
 * @param engine - The engine instance.
 * @param timeout_ms - Maximum time to process events, in milliseconds.
 *
 * @example
 * ```typescript
 * processEventsFor(engine, 100); // Process for up to 100ms
 * ```
 */
export declare export declare function processEventsFor(engine: QmltsEngine, timeoutMs: number): void

/**
 * Get the Qt runtime version.
 *
 * @returns Qt version string (e.g., "6.11.0").
 *
 * @example
 * ```typescript
 * console.log(`Qt ${qtVersion()}`);
 * ```
 */
export declare export declare function qtVersion(): string

/**
 * Request the Qt event loop to quit.
 *
 * @param engine - The engine instance.
 * @param exit_code - Optional exit code (default: 0).
 *
 * @example
 * ```typescript
 * quit(engine, 0);
 * ```
 */
export declare export declare function quit(engine: QmltsEngine, exitCode?: number | undefined | null): void

/**
 * Register a ViewModel bridge type by class name.
 *
 * Creates the bridge QObject pair and makes it available as `vm` and
 * `__qmlts` context properties in the QML engine. Must be called
 * before loading QML.
 *
 * @param engine - The engine instance.
 * @param class_name - ViewModel class name (e.g., "LoginViewModel").
 * @throws Error if the class name is not found or QML already loaded.
 *
 * @example
 * ```typescript
 * registerViewModel(engine, 'LoginViewModel');
 * loadFile(engine, './app/LoginView.qml');
 * ```
 */
export declare export declare function registerViewModel(engine: QmltsEngine, className: string): void

/**
 * Synchronize a single TypeScript property value into the active ViewModel.
 *
 * @param engine - The engine instance.
 * @param class_name - ViewModel class name (must match the active bridge).
 * @param property_name - Property name as declared in the schema.
 * @param json_value - JSON-encoded value to set.
 * @throws Error if the class name doesn't match, property not found, or type mismatch.
 *
 * @example
 * ```typescript
 * registerViewModel(engine, 'LoginViewModel');
 * syncState(engine, 'LoginViewModel', 'username', '"alice"');
 * ```
 */
export declare export declare function syncState(engine: QmltsEngine, className: string, propertyName: string, jsonValue: string): void

/**
 * Synchronize a batch of property values into the active ViewModel.
 *
 * Uses best-effort semantics: all properties are attempted, failures collected.
 *
 * @param engine - The engine instance.
 * @param class_name - ViewModel class name (must match the active bridge).
 * @param json_state_map - JSON object mapping property names to values.
 * @throws Error with details of any failed properties.
 *
 * @example
 * ```typescript
 * syncStateBatch(engine, 'LoginViewModel', '{"username":"bob","password":"secret"}');
 * ```
 */
export declare export declare function syncStateBatch(engine: QmltsEngine, className: string, jsonStateMap: string): void

/**
 * Get the QmlTS runtime version.
 *
 * @returns Version string (e.g., "0.1.0").
 *
 * @example
 * ```typescript
 * console.log(`QmlTS v${version()}`);
 * ```
 */
export declare export declare function version(): string
