/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * QmlTS Engine instance.
 *
 * This class wraps Qt's QGuiApplication and QQmlEngine.
 * It is created via `createEngine()` and automatically cleaned up
 * when garbage collected, or can be explicitly destroyed via `destroyEngine()`.
 *
 * @example
 * ```typescript
 * const engine = createEngine();
 * loadString(engine, 'import QtQuick; Item { }');
 * processEvents(engine);
 * destroyEngine(engine);
 * ```
 */
export declare class QmltsEngine {

}

/**
 * Activate a ViewModel by class name.
 *
 * Creates a new instance of the specified ViewModel and makes it
 * the active ViewModel for the engine. The ViewModel's properties
 * and commands become available via `getVmProperty`, `setVmProperty`,
 * and `invokeVmCommand`.
 *
 * @param engine - The engine instance.
 * @param class_name - The ViewModel class name to activate.
 * @throws Error if the ViewModel type is not registered.
 *
 * @example
 * ```typescript
 * activateViewModel(engine, 'CounterViewModel');
 * ```
 */
export declare export declare function activateViewModel(engine: QmltsEngine, className: string): void

/**
 * Add a QML import search path.
 *
 * @param engine - The engine instance.
 * @param path - Directory path to add to import search paths.
 *
 * @example
 * ```typescript
 * addImportPath(engine, './qml/imports');
 * ```
 */
export declare export declare function addImportPath(engine: QmltsEngine, path: string): void

/**
 * Add a Qt plugin search path.
 *
 * @param engine - The engine instance.
 * @param path - Directory path to add to plugin search paths.
 *
 * @example
 * ```typescript
 * addPluginPath(engine, '/opt/qt/plugins');
 * ```
 */
export declare export declare function addPluginPath(engine: QmltsEngine, path: string): void

/**
 * Create a new QmlTS engine instance.
 *
 * Initializes Qt's QGuiApplication (if not already initialized) and
 * creates a new QQmlEngine for loading and running QML documents.
 *
 * @param config - Optional engine configuration.
 * @returns A new QmltsEngine instance.
 * @throws Error if Qt initialization fails.
 *
 * @example
 * ```typescript
 * // Create with defaults
 * const engine = createEngine();
 *
 * // Create with custom paths
 * const engine = createEngine({
 *   importPaths: ['./qml'],
 *   enableLogging: true
 * });
 * ```
 */
export declare export declare function createEngine(config?: EngineConfig | undefined | null): QmltsEngine

/**
 * Deactivate the current ViewModel.
 *
 * Clears the active ViewModel. After calling this, `getVmProperty`,
 * `setVmProperty`, and `invokeVmCommand` will fail until a new
 * ViewModel is activated.
 *
 * @param engine - The engine instance.
 *
 * @example
 * ```typescript
 * deactivateViewModel(engine);
 * ```
 */
export declare export declare function deactivateViewModel(engine: QmltsEngine): void

/**
 * Destroy an engine instance.
 *
 * Explicitly releases engine resources. This is optional since the engine
 * will be automatically cleaned up when garbage collected.
 *
 * @param engine - The engine instance to destroy.
 *
 * @example
 * ```typescript
 * const engine = createEngine();
 * // ... use engine ...
 * destroyEngine(engine);
 * ```
 */
export declare export declare function destroyEngine(engine: QmltsEngine): void

/**
 * Drain all queued effects.
 *
 * @param engine - The engine instance.
 * @returns Array of effect IDs that were queued.
 *
 * @example
 * ```typescript
 * const effects = drainEffects(engine);
 * for (const effectId of effects) {
 *   // Trigger effect
 * }
 * ```
 */
export declare export declare function drainEffects(engine: QmltsEngine): Array<string>

/**
 * Engine configuration options.
 *
 * These options control Qt plugin/import paths and logging behavior.
 */
export interface EngineConfig {
  /** Qt plugin search paths. */
  pluginPaths?: string[] | undefined
  /** QML import search paths. */
  importPaths?: string[] | undefined
  /** Enable Qt logging forwarding. */
  enableLogging?: boolean | undefined
}

/**
 * Start the Qt event loop (blocking).
 *
 * This starts the Qt event loop and blocks until `quit()` is called.
 * Use `processEvents()` for non-blocking event processing.
 *
 * @param engine - The engine instance.
 * @returns Exit code from the event loop.
 *
 * @example
 * ```typescript
 * const exitCode = exec(engine);
 * console.log(`Exited with code ${exitCode}`);
 * ```
 */
export declare export declare function exec(engine: QmltsEngine): number

/**
 * Get the class name of the active ViewModel.
 *
 * @param engine - The engine instance.
 * @returns The class name of the active ViewModel, or null if none.
 *
 * @example
 * ```typescript
 * const vmName = getActiveViewModelName(engine);
 * // 'CounterViewModel' or null
 * ```
 */
export declare export declare function getActiveViewModelName(engine: QmltsEngine): string | null

/**
 * Get the list of registered ViewModel types.
 *
 * @param engine - The engine instance.
 * @returns Array of registered ViewModel class names.
 *
 * @example
 * ```typescript
 * const types = getRegisteredViewModels(engine);
 * // ['CounterViewModel', 'LoginViewModel']
 * ```
 */
export declare export declare function getRegisteredViewModels(engine: QmltsEngine): Array<string>

/**
 * Get the command names of the active ViewModel.
 *
 * @param engine - The engine instance.
 * @returns Array of command names.
 * @throws Error if no ViewModel is active.
 *
 * @example
 * ```typescript
 * const cmds = getVmCommandNames(engine);
 * // ['increment', 'decrement', 'reset'] for CounterViewModel
 * ```
 */
export declare export declare function getVmCommandNames(engine: QmltsEngine): Array<string>

/**
 * Get a property value from the active ViewModel.
 *
 * @param engine - The engine instance.
 * @param name - The property name.
 * @returns The property value as a JSON string.
 * @throws Error if no ViewModel is active or property not found.
 *
 * @example
 * ```typescript
 * const countJson = getVmProperty(engine, 'count');
 * const count = JSON.parse(countJson);
 * ```
 */
export declare export declare function getVmProperty(engine: QmltsEngine, name: string): string

/**
 * Get the property names of the active ViewModel.
 *
 * @param engine - The engine instance.
 * @returns Array of property names.
 * @throws Error if no ViewModel is active.
 *
 * @example
 * ```typescript
 * const props = getVmPropertyNames(engine);
 * // ['count'] for CounterViewModel
 * ```
 */
export declare export declare function getVmPropertyNames(engine: QmltsEngine): Array<string>

/**
 * Check if there is an active ViewModel.
 *
 * @param engine - The engine instance.
 * @returns True if a ViewModel is currently active.
 *
 * @example
 * ```typescript
 * if (hasActiveViewModel(engine)) {
 *   const count = getVmProperty(engine, 'count');
 * }
 * ```
 */
export declare export declare function hasActiveViewModel(engine: QmltsEngine): boolean

/**
 * Invoke a command on the active ViewModel.
 *
 * @param engine - The engine instance.
 * @param name - The command name.
 * @param args_json - Optional command arguments as a JSON string.
 * @returns The command result as a JSON string.
 * @throws Error if no ViewModel is active or command fails.
 *
 * @example
 * ```typescript
 * invokeVmCommand(engine, 'increment', null);
 * const result = invokeVmCommand(engine, 'login', '{"remember": true}');
 * ```
 */
export declare export declare function invokeVmCommand(engine: QmltsEngine, name: string, argsJson?: string | undefined | null): string

/**
 * Check if the runtime is mounted.
 *
 * @param engine - The engine instance.
 * @returns True if the runtime is mounted.
 *
 * @example
 * ```typescript
 * if (isRuntimeMounted(engine)) {
 *   // Component is ready
 * }
 * ```
 */
export declare export declare function isRuntimeMounted(engine: QmltsEngine): boolean

/**
 * Check if a ViewModel type is registered.
 *
 * @param engine - The engine instance.
 * @param class_name - The ViewModel class name to check.
 * @returns True if the ViewModel type is registered.
 *
 * @example
 * ```typescript
 * if (isViewModelRegistered(engine, 'CounterViewModel')) {
 *   activateViewModel(engine, 'CounterViewModel');
 * }
 * ```
 */
export declare export declare function isViewModelRegistered(engine: QmltsEngine, className: string): boolean

/**
 * Load a QML document from a file.
 *
 * @param engine - The engine instance.
 * @param path - Path to the QML file.
 * @throws Error if the file is not found or contains QML errors.
 *
 * @example
 * ```typescript
 * loadFile(engine, './app/Main.qml');
 * ```
 */
export declare export declare function loadFile(engine: QmltsEngine, path: string): void

/**
 * Load a QML document from a string.
 *
 * @param engine - The engine instance.
 * @param qml_source - QML source code.
 * @param base_url - Optional base URL for resolving relative imports.
 * @throws Error if the QML contains syntax errors.
 *
 * @example
 * ```typescript
 * loadString(engine, `
 *   import QtQuick
 *   Item {
 *     width: 400
 *     height: 300
 *   }
 * `);
 * ```
 */
export declare export declare function loadString(engine: QmltsEngine, qmlSource: string, baseUrl?: string | undefined | null): void

/**
 * Process all pending Qt events.
 *
 * This processes the Qt event queue and returns immediately.
 * Call this in a loop or timer for non-blocking event processing.
 *
 * @param engine - The engine instance.
 *
 * @example
 * ```typescript
 * // Non-blocking event processing
 * setInterval(() => processEvents(engine), 16); // ~60fps
 * ```
 */
export declare export declare function processEvents(engine: QmltsEngine): void

/**
 * Process Qt events for up to the specified duration.
 *
 * @param engine - The engine instance.
 * @param timeout_ms - Maximum time to process events, in milliseconds.
 *
 * @example
 * ```typescript
 * processEventsFor(engine, 100); // Process for up to 100ms
 * ```
 */
export declare export declare function processEventsFor(engine: QmltsEngine, timeoutMs: number): void

/**
 * Get the Qt runtime version.
 *
 * @returns Qt version string (e.g., "6.11.0").
 *
 * @example
 * ```typescript
 * console.log(`Qt ${qtVersion()}`);
 * ```
 */
export declare export declare function qtVersion(): string

/**
 * Queue an effect to be triggered.
 *
 * @param engine - The engine instance.
 * @param effect_id - The effect ID to queue.
 *
 * @example
 * ```typescript
 * queueEffect(engine, 'effect_1');
 * ```
 */
export declare export declare function queueEffect(engine: QmltsEngine, effectId: string): void

/**
 * Request the Qt event loop to quit.
 *
 * @param engine - The engine instance.
 * @param exit_code - Optional exit code (default: 0).
 *
 * @example
 * ```typescript
 * quit(engine, 0);
 * ```
 */
export declare export declare function quit(engine: QmltsEngine, exitCode?: number | undefined | null): void

/**
 * Set a property value on the active ViewModel.
 *
 * @param engine - The engine instance.
 * @param name - The property name.
 * @param value_json - The property value as a JSON string.
 * @throws Error if no ViewModel is active, property not found, or type mismatch.
 *
 * @example
 * ```typescript
 * setVmProperty(engine, 'count', '42');
 * setVmProperty(engine, 'username', '"testuser"');
 * ```
 */
export declare export declare function setVmProperty(engine: QmltsEngine, name: string, valueJson: string): void

/**
 * Get the QmlTS runtime version.
 *
 * @returns Version string (e.g., "0.1.0").
 *
 * @example
 * ```typescript
 * console.log(`QmlTS v${version()}`);
 * ```
 */
export declare export declare function version(): string
