import type { AstNode } from '../ast/index.js';

// ─── Emit Options ────────────────────────────────────────────────────────

export interface EmitOptions {
  indentStyle?: 'spaces' | 'tabs';
  indentSize?: number;
  newline?: '\n' | '\r\n';
  maxLineWidth?: number;
  insertBlankLinesBetweenSections?: boolean;
  insertBlankLinesBetweenObjects?: boolean;
  insertBlankLinesBetweenFunctions?: boolean;
  quoteStyle?: 'double' | 'single' | 'preserve';
  emitComments?: boolean;
  emitGeneratedHeader?: boolean;
  generatedHeaderText?: string;
  trailingNewline?: boolean;
  normalize?: boolean;
  sortImports?: boolean;
  singleLineEmptyObjects?: boolean;
  semicolonRule?: 'omit' | 'always' | 'essential';
}

export interface FragmentEmitOptions extends EmitOptions {
  indentLevel?: number;
}

export interface ResolvedEmitOptions {
  indentStyle: 'spaces' | 'tabs';
  indentSize: number;
  newline: '\n' | '\r\n';
  maxLineWidth: number;
  insertBlankLinesBetweenSections: boolean;
  insertBlankLinesBetweenObjects: boolean;
  insertBlankLinesBetweenFunctions: boolean;
  quoteStyle: 'double' | 'single' | 'preserve';
  emitComments: boolean;
  emitGeneratedHeader: boolean;
  generatedHeaderText: string;
  trailingNewline: boolean;
  normalize: boolean;
  sortImports: boolean;
  singleLineEmptyObjects: boolean;
  semicolonRule: 'omit' | 'always' | 'essential';
}

export const DEFAULT_OPTIONS: ResolvedEmitOptions = {
  indentStyle: 'spaces',
  indentSize: 4,
  newline: '\n',
  maxLineWidth: -1,
  insertBlankLinesBetweenSections: true,
  insertBlankLinesBetweenObjects: true,
  insertBlankLinesBetweenFunctions: true,
  quoteStyle: 'double',
  emitComments: true,
  emitGeneratedHeader: false,
  generatedHeaderText: 'Generated by QmlTS',
  trailingNewline: true,
  normalize: false,
  sortImports: false,
  singleLineEmptyObjects: true,
  semicolonRule: 'omit',
};

export function resolveOptions(options?: EmitOptions): ResolvedEmitOptions {
  if (!options) return { ...DEFAULT_OPTIONS };
  return { ...DEFAULT_OPTIONS, ...options };
}

// ─── Source Map Types ────────────────────────────────────────────────────

export interface OutputSpan {
  startLine: number;
  startColumn: number;
  endLine: number;
  endColumn: number;
}

export interface SourceMapEntry {
  node: AstNode;
  nodeKind: string;
  outputSpan: OutputSpan;
}

export interface SourceMapJSON {
  entries: {
    nodeKind: string;
    startLine: number;
    startColumn: number;
    endLine: number;
    endColumn: number;
  }[];
}

export interface SourceMap {
  readonly entries: SourceMapEntry[];
  getOutputSpan(node: AstNode): OutputSpan | undefined;
  getNodesAtLine(line: number): AstNode[];
  getInnermostNodeAt(line: number, column: number): AstNode | undefined;
  toJSON(): SourceMapJSON;
}

export interface EmitWithSourceMapResult {
  text: string;
  sourceMap: SourceMap;
}
